### ISSUE TITLE
関数は長く書いてはいけないことを記述

### ISSUE THREAD

**Issue by yumetodo** [yumetodo/2015_C_Textbook#14]
**関数の型より前に**記述する。

http://www.pro.or.jp/~fuji/mybooks/cdiag/cdiag.3.4.html

http://www.pro.or.jp/~fuji/mybooks/cdiag/

を参考に

**Comment by yumetodo** [comment]
書き終えてるならcloseしてください

**Comment by Kamioda** [comment]
記述完了してたけどクローズ忘れてた
