### ISSUE TITLE
カテゴリを分ける

### ISSUE THREAD

**Issue by yumetodo** [yumetodo/2015_C_Textbook#60]
#51 より。
- ./2015_C_Textbook/

以下にhtmlをおいているのを
- ./2015_C_Textbook/c/
- ./2015_C_Textbook/advc/
- ./2015_C_Textbook/cpp/

に分ける。具体的構成は #51 で議論中

**Comment by yumetodo** [comment]
# 構成(仮)

章分けはとりあえず後回し。(advcの中以外は一応順番は意識して列挙してある)
- C  
  - main関数の書き方
  - コメントの書き方
  - arikitari_na_world!(Hello world!)
  - 自動変数とスコープ
  - 代入とは
  - 変数の型
  - 予約語
  - cv修飾子
  - signed/unsigned
  - typedef
  - stdint.h
  - lvalueとrvalue
  - 算術型リテラル
  - 文字リテラル
  - 3つの型変換
  - 文字列リテラル
  - 算術演算
  - 論理演算
  - 関数
  - main関数の引数
  - 関数は分割せよ
  - 再帰
  - bool型とstdbool.h
  - 条件文
  - if文
  - 三項演算子
  - Switch文
  - enum
  - while
  - for
  - do-while
  - ジャンプ文
    - continue/break
    - gotoとgoto害悪論
  - ソースファイルの分割と翻訳単位とinline
  - プリプロセッサ
  - 定数
  - ポインタ  
    - &演算子
    - ポインタとcv修飾子
    - NULLポインタ
  - 関数ポインタ
  - 構造体とaggregateとリスト初期化
  - union
- ADVC  
  - 関数の呼び出される過程(アーキテクチャ依存が出るのは仕方ない気がする)
  - 配列
  - 配列とaggregateとリスト初期化
  - 多次元配列
  - 構造体とポインタ(詰め物の理由)
  - 動的確保
  - 文字列とは
  - 文字列操作
  - 標準入出力
  - static修飾子、グローバル変数
  - (C11の)マルチスレッド
  - あとは(　@173210　)に任せた(ぇ)
- C++
  - Cとの違い
  - 例外
  - name space
  - enum class
  - constexpr
  - auto型推論
  - alias declaration
  - 戻り値の型の後置(C++11)とauto推論(C++14)
  - lambda
  - 関数のオーバーロード
  - operator orverload
  - std::string
  - 標準入出力
  - std::array
  - iterator
  - Range-based for
  - lvalue Reference
  - std::vector
  - class  
    - アクセス指定
    - aggregateとリスト初期化
    - constructorとdestructor
    - copy/move constructor/assignment operator
    - 暗黙のconstructor
    - member function
    - friend
    - Cの構造体との関連性とPOD
  - std::unorderd_map
  - template関数
  - template class
  - 関数オブジェクト(function-like class)
  - templateの特殊化
  - 可変長template
- MISC
  - tarminal(console)についての基礎知識
  - 乱数

**Comment by 173210** [comment]
@yumetodo 呼び出し規約は`C`でやりませんか。関数型言語でないC言語で再帰呼出しするとヤバイこと、関数呼び出しのオーバーヘッドが説明できませんから。自動変数の前や一緒に書いておくと良いかもしれません。どうせスタックの話になるので。
アーキテクチャ依存はなんとかします。ただ自分の頭はARMとMIPS, 時々PowerPCで動いているので、x86で違うことがあったら言ってください。

あと動的確保の内容とstatic修飾のローカル変数、グローバル変数の一部を自動変数の項に持っていけませんか。どのメモリ割り当てがどのように良くてどのようにクソなのかはやはりまとめて書いておくべきだと思うんです。
例えば、`malloc`と`free`、`static`修飾のローカル変数、グローバル変数（ただし`extern`と`static`抜き）の内容を書いて、実際に使いたいという場合には`ADVC`を見よと書いておけばよいかなと。

マルチスレッドいるかなあ。どうせその環境のものを使うので。まあたいていPOSIXですけどね。

**Comment by yumetodo** [comment]
呼び出し規約は忘れてた。C++のクラスのメンバ関数を語るのに呼び出し規約の話は避けて通れないのでお願いします。というか
http://yumetodo.github.io/2015_C_Textbook/05function.html
なんでここから関数呼び出し規約の文字が消えたし

うーん、ただ関数の説明より後にしないと`malloc`/`calloc`と`free`の説明ができないですね・・・。バラけるなぁ・・・。

まあ9年くらい前からMTが有名になりましたし。ただMTしても速くするのは噂みたいには全然簡単じゃない、という話を伝えたいかなと。(なおC11のMTは使ったこと無い、C++11のは使ったことあるけど)

**Comment by 173210** [comment]
「関数と変数」で１つの章にして、関数と自動割り当てについて説明して、その次の章で「静的割り当てと動的割り当て」でグローバル変数や`malloc`について説明すれば良いかなと思います。

標準Cライブラリにはいろいろ機能があるので、マルチスレッディングだけ特筆することはないかなと思います。
`advc`で「標準Cライブラリ」という章を作ってその中に概要だけのせるのはどうでしょう?必要な関数があるのがわかればあとはググればなんとかなりますから。

**Comment by yumetodo** [comment]
その場合型の話もするわけで、・・・なんか盛りだくさん！

> マルチスレッディングだけ特筆することはないかなと思います。

特筆性はあると思うんですが、まあ後で改めて考えましょう。そこは大事なとこではないし。

**Comment by 173210** [comment]
8e27d85f3900f1ae375049a5a06f34d7274c09ee で、Jekyllの仕様に合わせて直下にあった全ての記事を`_c`ディレクトリに移しました。Jekyllでは`c`カテゴリとして認識され、`{{ site.url }}/c`以下で公開されます。同様に`misc`ディレクトリにあったものは`_misc`ディレクトリに移され`misc`カテゴリとなりました。

**Comment by yumetodo** [comment]
目次自動生成は嬉しい。
いま、第0章となっているもの、あとでCではなくMISCに持って行きますか。CとC++で説明かぶるし。

**Comment by 173210** [comment]
スタックを説明しなくても自動変数にみられるプログラマ側からの制約を説明するだけでなんとかなりますね。
e511a359a5d102dbe52527b8cb11d6be016ce692

**Comment by 173210** [comment]
構成, 章分けを`c`と`advc`, `misc`の部分で考えてみました。他に提案がなければ決定して欲しいです。

# c

## 1. コメント

### 書き方

### 注意

## 2. 関数

### 関数とは

戻り値、引数を説明するため型についての簡単な説明を含む

### main関数の書き方

### 関数を定義する時

関数は分割せよ

## 3. ライブラリ

### プロトタイプ宣言とヘッダファイル

#includeについてもプリプロセッサに触れずに解説

### C標準ライブラリ

ヘッダファイルのリストと簡単な使い方

## 4. 変数

### 宣言

### 代入

### 初期化

### 型

### 型の表せる範囲

### 型の大きさ

### signedとunsigned

### typedef

### stdint.h

### const

### volatile

### 整数リテラル

### 文字リテラル

### 自動変数

## 5. 算術演算

### 算術演算子

### 型変換

暗黙の型変換とキャスト

### 型変換に関する注意

## 6. 論理演算

### 論理演算とビット演算

### 左シフト

### 右シフト

### 論理積

### 論理和

### 排他的論理和

## 7. 条件文

### 条件文

### if文

### 三項演算子

### switch文

### enum

### bool型と_Bool型

## 8. ループ

### while文

### for文

### do-while文

### breakとcontinue文、gotoと構造化プログラミング

### 再帰呼出し

## 9. プリプロセッサと定数

### プリプロセッサ

### #define

### #includeとインクルードガード

### 定数

## 10. 標準入出力を扱う

### 標準出力を扱う

### 標準入力を扱う

### ファイルストリームとして標準入出力を扱う

## 11. ポインタ

### 変数のアドレス

### ポインタ

### &演算子

### NULL

### ポインタと修飾子

### 文字列リテラル

### main関数の引数

## 12. 配列とポインタ演算

### 配列

### ポインタ演算と添字演算子

### バッファオーバーラン

## 13. いろいろなポインタ

### 関数ポインタ

### 配列のポインタ

### 多次元配列

## 14. 構造体とunion

### 構造体とその定義

### アロー演算子とドット演算子

### union

## 15. リンク

### 翻訳単位

### リンゲージ

### ヘッダファイル

こちらは書き方。inline等も合わせる。

# advc

アーキテクチャ依存が出る部分は命令が簡単で実用のMIPSを。
(本音はARMを使いたいが多分学んだことがない人には厳しい)

## 1. 関数呼び出しとスタック

### メモリとレジスタ

### スタック

### 呼び出し規約

## 2. 静的割り当てとグローバル変数

### 静的割り当て

書き方

### 利点と欠点

### グローバル変数

### グローバル変数の利点と欠点

## 3. 動的割り当てとヒープ

## ヒープ

## 動的割り当てに使う関数

### 利点と欠点

## 3. 構造体とパディング

# MISC

## プログラミングを始める前に

### プログラミング言語とはなにか

### C言語の簡単な歴史

### C言語の特徴

### 実行順序

### 開発の流れ

### ビルドの流れ

### Cコンパイラ

### プログラミングの鉄則

## 標準入出力

### 端末

## 標準出力

## 標準エラー出力

## 標準入力

## ファイルストリーム

**Comment by yumetodo** [comment]
変数の説明より先に関数って説明できるものなんですかね・・・。

https://yumetodo.github.io/2015_C_Textbook/c/02function.html

これ見たけどなんかピンときてくれなさそう、読んだ人が。

**Comment by 173210** [comment]
@yumetodo 具体的にどの部分が? 変数については、型を関数の部分で一部説明すれば十分だと思っています。

現在の構成だとどちらかというと変数以外に関する部分が問題な気もします。`printf`/`puts`が使えないので、結果を確認することができません。また、そういった制約のため、やや複雑なコードを書くこともできないので構造化プログラミングについての説明を、実例を示して行うことができません。

**Comment by yumetodo** [comment]
@173210 一眠りして改めて考えたら、関数が先でもいいか、という気はしてきた。

ただ、各章に積極的に関数分けさせるように練習問題は付けたいが、それは構成とは関係ないお話なのでまあいいや。

**Comment by 173210** [comment]
じゃあこれでいいですかね? 他に何か現時点で変えるべきところはありますか?

**Comment by yumetodo** [comment]
MISCの、Cの歴史はCとC++分ける意味がわからないので混ぜて書きたいですね。双方影響を受けたわけで。

**Comment by 173210** [comment]
@yumetodo 冗長になりませんか。最初見た時にすごく長かったのでバッサリC++関連を削除したんですよね。
CとC++が違うものだからを分けるということではなく、長すぎるので。

**Comment by 173210** [comment]
とりあえず`c`と`advc`はそれで決定しますね。

**Comment by yumetodo** [comment]
歴史については昔のあれを長さ半分くらいに再編集して、CとC++合わせて書いてしまおうかと

**Comment by 173210** [comment]
カテゴリ分けは出来たのでissueを別に立てたほうがいいですね。

**Comment by 173210** [comment]
`misc`の章立てについては #71 で。このissueは閉じます。
