### ISSUE TITLE
Jekyllを利用

### ISSUE THREAD

**Issue by 173210** [yumetodo/2015_C_Textbook#61]
ヘッダ、フッタが全部のHTMLにコピーされていて汚いのでJekyllで自動化しましょう (後で)
Jekyllは静的Webページ生成ツールで、GitHubはそれに対応しているので、変換前のものをプッシュすると自動的に変換してくれます。
https://jekyllrb.com/

**Comment by 173210** [comment]
他のプロジェクトが他人待ちでブロックしているのでこれの実装を開始しました。プロトタイプができたので真面目なものにしてみます。

**Comment by yumetodo** [comment]
お願いします。

**Comment by 173210** [comment]
8e27d85f3900f1ae375049a5a06f34d7274c09ee で完了。ある程度のコードの削減に成功。

> 2,962 additions and 3,388 deletions.
