### ISSUE TITLE
common.jsが読み込まれていない

### ISSUE THREAD

**Issue by yumetodo** [yumetodo/2015_C_Textbook#64]
common.jsにある`change_answer_state`関数が呼べていないので、ボタンを押して答えを表示している部分が死んでいる

**Comment by 173210** [comment]
8e27d85f3900f1ae375049a5a06f34d7274c09ee で吹き飛んだ模様。

**Comment by yumetodo** [comment]
なおします

**Comment by 173210** [comment]
Jekyllが関わるので、どうした方がいいか。
`use_change_answer_state`とかいう変数を追加するか。それともJekyll使わずに記事に直書きするか。

**Comment by yumetodo** [comment]
うーん、直書きでもいいと思うんですが。

**Comment by 173210** [comment]
分かりました。お願いします。
なお、相対パスにせず`{{ site.url }}`使うといいですよ（詳しくはhttps://jekyllrb.com)

**Comment by yumetodo** [comment]
ええい、ミスっとるがな

**Comment by 173210** [comment]
> css

Oh

**Comment by yumetodo** [comment]
こんどこそいいだろう・・・。おのれ予測変換。というかfixって文字があったらcloseされんのか。

**Comment by 173210** [comment]
修正できてます。手間かけてすみません。
