### ISSUE TITLE
Jekyll 3のsite.collectionsのAPI変更への対応

### ISSUE THREAD

**Issue by 173210** [yumetodo/2015_C_Textbook#72]
なおGitHub Pagesでは生成できている。

```
$ jekyll serve
Configuration file: /home/root3/Documents/2015_C_Textbook/_config.yml
            Source: /home/root3/Documents/2015_C_Textbook
       Destination: /home/root3/Documents/2015_C_Textbook/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid error: Cannot sort a null object. in index.html
$ jekyll --version
jekyll 3.0.1
```

**Comment by 173210** [comment]
[Collections](http://jekyllrb.com/docs/collections/)

> Collections support is unstable and may change
> 
> This is an experimental feature and the API may change until the feature stabilizes.

API変更、踏んじゃったかなあ。

**Comment by 173210** [comment]
現在のJekyll最新版3.1.1でも同様の問題が発生。GitHubのJekyllのバージョンは3.0.1とのこと。Jekyll本体の問題ではないかもしれない。
[Dependency versions - GitHub Pages](https://pages.github.com/versions/)

**Comment by yumetodo** [comment]
null objectってなんじゃらそい

**Comment by 173210** [comment]
https://github.com/yumetodo/2015_C_Textbook/blob/8e27d85f3900f1ae375049a5a06f34d7274c09ee/index.html#L57
この`site.collections["c"].docs`がぬるぽに。

**Comment by 173210** [comment]
[Upgrading from 2.x to 3.x](http://jekyllrb.com/docs/upgrading/2-to-3/#sitecollections-has-changed)に従って 4edf580ad51dbf6f1f4d8d1444d5461448095a39 で解決。

# しかしなんでGitHub Pagesは影響ないんだろうなあ。

**Comment by yumetodo** [comment]
なにやら手を加えてるのかもしれない、互換性のために。

**Comment by 173210** [comment]
`article_nav`でも発現しているのが確認できました。ところで、今見たら`article_nav`ではGitHub Pagesでも発現しています。つまり、更新をサボってたから発現してなかっただけということ…うっ

**Comment by 173210** [comment]
5814c3f5b76b20f039323d3bd7657b0b31400587 で`article_nav`を修正。closeします。
